Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -71,12 +71,20 @@ jobs:
         with:
           host: ${{ secrets.VPS_HOST }}
           username: ${{ secrets.VPS_USERNAME }}
-          password: ${{ secrets.VPS_PASS_KEY }}
+          key: ${{ secrets.VPS_SSH_PRIV_KEY }}
+          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
           script: |
             docker pull ${{ secrets.DOCKER_USERNAME }}/plopster-land-img:latest
             docker stop plopster-land-container
             docker rm plopster-land-container
             docker run -d --name plopster-land-container -p 8001:80 nicodav28/plopster-land-img:latest
-
+            
+            if docker ps | grep yor-bot-dc-container; then
+              echo "Container is running successfully"
+            else
+              echo "Failed to start container"
+              exit 1
+            fi
+            
       - name: Prune System
         run: "echo y | docker system prune -a"
